### PR TITLE
add dependencyCheck

### PR DESCRIPTION
**Pull request by michield**
add a list of dependencies that are checked before the plugin can be enabled.

### CODE REVIEW

**Comment by bramley** [comment]
Is the dependency check something new in the next release of phplist?
Is each array entry a condition that gets evaluated? If so, can I also include a test for CommonPlugin being installed, something like

    phplistPlugin::isEnabled('CommonPlugin')
and possibly the php version too.

What is the difference between VERSION and getConfig('version'), which I use elsewhere in the plugin?
It is probably safer to use the php function version_compare() instead of a string comparison, as that is aware of the "semantics" of the version, major, minor etc. Using a string comparison 3.0.9 is greater than 3.0.10.

But I don't understand the dependency on phplist later than 3.0.10, I wasn't aware of any problem with earlier versions.

**Comment by michield** [comment]
Yes, it's new, I just added it. https://github.com/phpList/phplist3/commit/79581eab0e602412ee68a79b874acb13a0bc5a17

VERSION is the constant defined in the code. getConfig returns the DB value, which may differ (when upgrade hasn't been called yet).

Yes, true, using version compare is probabably better. I will update that.

I'm about to commit an additional check on the common plugin being available.

Sure, the plugin works with earlier versions, but as the check is only added now, it can be tested like this. In fact the test should be 3.0.12

**Comment by michield** [comment]
ok, updated a little

**Comment by bramley** [comment]
I think that using eval is a bit clunky, putting php code into a string. An alternative is to have a method that returns an array so that the conditions are evaluated as normal php code

    function dependencyCheck()
      {
          return array(
            'phpList version' => version_compare(VERSION, '3.0.12') >= 0
          );
      }

This would also allow more complex dependencies to be evaluated.

**Comment by michield** [comment]
updated to use the new mechanism

**Comment by bramley** [comment]
Applied with some minor changes.

**Pull request closed without merging**
